creation_rules:
  # Staging k8s secret manifests — same age keypair as prod (infrastructure/kubernetes/)
  - path_regex: infrastructure/kubernetes/staging/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
  - path_regex: secrets/staging/.*\.yaml$
    age: age1d77gyptx7kns6mx2mfsk8wwdpnaw97khkyyft9shdmslyzmkcguqq2g8ym
  - path_regex: secrets/prod/.*\.yaml$
    age: age1d77gyptx7kns6mx2mfsk8wwdpnaw97khkyyft9shdmslyzmkcguqq2g8ym
