creation_rules:
  - path_regex: secrets/staging/.*\.yaml$
    age: age1d77gyptx7kns6mx2mfsk8wwdpnaw97khkyyft9shdmslyzmkcguqq2g8ym
  - path_regex: secrets/prod/.*\.yaml$
    age: age1d77gyptx7kns6mx2mfsk8wwdpnaw97khkyyft9shdmslyzmkcguqq2g8ym
