# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic
sqlalchemy.url = %(DATABASE_URL)s

# template for migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path entries, comma separated
# prepend_sys_path = .

# timezone for logging purposes
timezone =

# max length of characters to apply to the
# "slug" field
# slug_max_length = 40

# set to 'true' to run the environment during
# the 'check' phase, assuming revision is recent
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files
# within the versions/ directory
# sourceless = false

# The Alembic loggers
# ... below are the default loggers, which can be customized as needed.
#
[loggers]
keys = root,alembic,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

# A handler that logs to the console
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

# A formatter for console output
[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S