apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets-staging
    namespace: meeting-automation-staging
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:i+4+OnzSItqgg7kw/UJ8KnjEmwvh6eQnmmMOt/zUFxK/L0pp96bdZZhXhclVTHYmDWGHst4COpTTlxgiJNznJzAzGyt0oOZ226KB6gxMGXJ5OV0U2A9VuKz9CVHrHVUVondC/TD6W/JPch0VOF/cyt5iayMPHNg1TYh2UIlew0+KO3MkHQ==,iv:t0k0uZitkeIGyQspPFjvg0I98YpihKEjJmopLj8fxdQ=,tag:+jM+16ROTWh/uaFEFr2DQA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:3Kci3XYdMjD+EiIBHTri/4BFs8vC4YshB5ZFxZujxmD5tajC5GbRG7p992zK8goeP1sxg+IzcuWe9qtrPcv7WKyKjwX/DRk5atKPb+eCZ556kl/xmPEM9vs=,iv:u289rX0qsTQahbyenxp29yu5U/QFFcXhYwvzmuBHNN0=,tag:0pZ5lMvNxjEtkamtLrWb1A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:DbIKs4PJm5oM/LRzJE/AdxU4SZvWDWlHg4tAaeiuNCrxBwVNcMmbHvf/RrvfdF8iTg==,iv:X7CIo1gnyyMWcMa0tORuf5LBoyaZKLMdRh5P03gYPD4=,tag:Ns0imOOBDwi+2lniAGgavQ==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:jti+0TpKSx4d8Q==,iv:i/d/unyuL9UAoHhjY3EyErFONJSgu99o9VRwweiZeuo=,tag:dKZ++6dRnuPbPG56dePUsA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:wNnezXTtv8A0Gl4DlD8=,iv:1HdocaeHyedR3dqa1MB1wBJzE/nsonBOHeRv/2MUwtQ=,tag:/YcBFqxfZGQYEfIVFma5KQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:JExupQausiNXef9KZhWlUflGFQWCy+mLCEzhOMU37+YC6nRTz5ubhfGDl0I=,iv:zV9gH7tWSBlBglRyf0Jh85IqkjRHgA6HB0HxSW83Ep0=,tag:NoivKP5WoJ78F2p2Ia052g==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:rhD6g+oJcpVsMd19PN0yniFvXv26ag8ZQHSrTpJ4wZM=,iv:0PSYWOfXbxdwlKaGvH5gKlGYtX32TX0hKPOP6Fgu+YM=,tag:WrHlsgSPoyHvlG11dfGDeg==,type:str]
    GLADIA_API_KEY: ENC[AES256_GCM,data:9UcqDKRvVDTzdgmwz6bF0VJVubK0iT30coSDwLurz3cPDfdgHTKvCGJF,iv:XLVh8TJo/3++uUNacDHmUpLiSkmf5uqRVNvURw7tef4=,tag:sWhNyXeBYE4Xzu40JH9doQ==,type:str]
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:YI0LIAPVSvsvbTH6cUkC,iv:yiV0kK+xSI/sAT0Vk8Q7OHnIrmtPKgki5zCLPuOlhJY=,tag:kt2oaJNJQ2B8/1y+3MB6uw==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:XD670qiVY86nowjLyLqUSCywTD528sleRAnk0fkUBeMWr1c6xfM7KAg=,iv:taD9EHfyzdWG/spbVlOizCjCLXh5OxZwwKyPlAO4X7M=,tag:2+hlGxdqpnOkym0xHvXvDA==,type:str]
    N8N_WEBHOOK_URL: ENC[AES256_GCM,data:OqQhGNng4pGVluEurz4GmgR5s09U82+OxGCKKLkoVA==,iv:mKdyZB+J7ThVi77BUuIqkOuo5a1/jR4l8/lcokLQAus=,tag:3zHuwj3fln/um+LyCX0akA==,type:str]
    ONLYOFFICE_URL: ENC[AES256_GCM,data:rD/3AGnMJmObV3yOAqTk+gBw2UQAqyh+WlSsYQ==,iv:lIALRm58K2042M5c9+EXS6qmq5f4436iTvztlDE/BLg=,tag:e1khDp8q9cN2IB/R6NfmaQ==,type:str]
    ONLYOFFICE_SECRET: ENC[AES256_GCM,data:VM+694vvOM3LS9MYMo+L/MZ4na660Ak/F9B/YwYLYBn+FauZEt4=,iv:841Zp5EGQqhVXYvVNmjwf6fLZpKrTqnzO1hI3NKVm2s=,tag:nCHsh2LCKkbEO55v4ZN63w==,type:str]
    PUBLIC_BACKEND_URL: ENC[AES256_GCM,data:fZ64eyP0ylRcsVba18/FRue4I9oQSme0oglnlXdTa34An2qBbJDfxw9N7hK4mZkTIcV8mop4m2zX+g3YAmNBMw==,iv:HxHYBR7JrK+6+KmT3yokEv+7VCN4FFEISpviLcuhCVo=,tag:FphDTB9P31NPnJuPw/7FXQ==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:fdseNcYuPKZgdmMB/cdW6VRoA3wKiMneIuonVVKzwh4kKsPFWQpolf9HVKiW6w+/DgLKpRJGgYCZbLOPQQDkQMsUHEcknlM5tDXQiHqdkHAciObKePPmfnQfvzvQqgmOtMskO26b2g==,iv:AF8mpyNn3gndoEek/2NeWw6nd4E+DeoVB5oHodisyF8=,tag:B26nDoKMgKBtgjcf/PgRSA==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:4L3vsWPkAt9tNX/RrLgpQ6mDM1Bg7v8xsUQcBH1EkBwEuDyG60xeneEpkSRlgtE7UQghtfqBhEplgdHidfHEZKe3Jnbzb1S8mS/TpoFFJrBKbomXol5eQIk=,iv:cobWMo/+SVJiQBM0TM04cikwHdu+xEVAkSxiVtPBsrI=,tag:fiIc7k/YBniFCln8/0IofQ==,type:str]
    E2E_TEST_USER_EMAIL: ENC[AES256_GCM,data:aHF4JE2RcDs1lrsaFme9KA254VgQJagXluMHNzM=,iv:YWqR238ChrlXEISRMFh3uQCiMLyUE0O92eFC3YMrnOQ=,tag:qrIGjmukAov5+Y33+q5XNw==,type:str]
    E2E_TEST_USER_PASSWORD: ENC[AES256_GCM,data:sNBlRI1OxO0u9/NN,iv:ZtbxWTZOKyiN3bUjK8WBg315xuXGaC8zWbZNNyux1zs=,tag:+a19t0JVOvOyEHMjfiygVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwckFqN3FUd2ZuVnpaaXBi
            WGl3bzVWS2MzZGxxcFN1eTdqMU1xZGRIN0hzCkthZ25FSGZYK1ZJclFlYnhxcEVY
            SkhZTGZKd1A1bi8xQno3eWZKZW1paGsKLS0tIFFwb0s2Uk5semF5ck1NL2hOY3p6
            UExrSndpNE5VYWNvdkNWVE1pN3NXYW8Kl+VNsyWOY+aoHbQTXMEI/E5Q1Lf6og48
            +UezxgNm7NfBia5r9Kq8txaTuknNY/tJaqu67Z+Ix7W9zBgLisCKzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:54Z"
    mac: ENC[AES256_GCM,data:/cE1Cm1mk8WtmV0SpgFp6OYi4lEXaULSPvIsOC5PoC5TydmvCuPk1vYQnoRffGJ3cy2XQu8fHaq39dMWpzSeXu73v3x3ZbO8FedAJNMAyB6XQyDFFDyQNG5K2I4ewEFoUWDWEZZXZEw7BWTvpkdMMG75VRdkcNFmpHiRG+qPXR0=,iv:ZC90C/BxkEGJag6PD+NC+oHaq+qTozI5MS1LDvgsIn4=,tag:qOyp8cm+zrErbsGGeDuO/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
