apiVersion: v1
kind: Secret
metadata:
    name: livekit-secrets-staging
    namespace: meeting-automation-staging
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:gRS+q3iytsCAdzJcgXx8,iv:NL9CZTiFjzOkFwm33lZV0PttbWFycBiyldsXFkP8XT4=,tag:Cw7ccMsuJemD0Kw9/u76ig==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:IYkBNoDwwf8icS2mBwMnyTQgv4JrJdfK581mmy3H/l/L6tLBcaKrPxM=,iv:FcMPfgX6O4sRwtHrZqDWD8QdbG6gpMk0mJH8pBfMRjo=,tag:C18X7/eAIwE+Yysz8kF9gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVlFueFVsRTFuNjJHQnVr
            dDNrWE5lWm5Ba0kzWFQzV2pJbkxMbnBYaWhJCkcxem5WRjg5ODR6M2MxTDExb3Js
            OHRuTllVbzcwdWlWZFBveDdzM1ZZYVEKLS0tIHVjRmg0TEJIWHYvV3llbmpqbUVt
            U0F4Y2FuWER0NHNYcUdLZGlJZlNMbWcKImBva212W1JjN/IoCn2L3CTob5gFOcga
            eOnI7J/noMastrfPJoDHJTU7Vu1z5JiDJ/zGkny6ONBNDY6caqi0bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:54Z"
    mac: ENC[AES256_GCM,data:VbSyaEKA+5rGMrxnBr2Glra9iFMQStVHfwpJJ81FZJFMRMHao76N5QrOKAvSbLPKYFQjb8oBkCeFtjLnVSoe0QtqPYU8eIvroHYmQjKztLA86BjLgINWsSJjnXMJ6n4pc8vYiXh9rEnt1sCFbfKhYSGarpsURpG27bRAiXTafss=,iv:9w+RF5ACz8WG8F3K6SfX4ofbdax+5+l6M/rwwhADbAs=,tag:EfscmQ5hGFb1mToAtvry2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
