---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: meeting-automation-staging
type: Opaque
stringData:
  MINIO_ROOT_USER: minio_user_staging
  MINIO_ROOT_PASSWORD: minio_password_staging_2026
