apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: meeting-automation-staging
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:k6O7xqYlFaOexQ==,iv:nlp/zYbOpltJmBb2O0Z7N9bAokoHSiOD8GrAdmvWMnw=,tag:KQg84kRW0O2d+t5cwZIgFQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:VREKNCcoJIb6pEcCyXQ=,iv:QelUoG7JtCpQUJnpYCdJqYHepQVjPAm1LWgMzwld+xo=,tag:gQYvhrIRHgg0QW+UMnjfiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cWMxWm9VMEZ1WWJkUVFK
            STBhUFBjNW5iZ0dxU21Bc1hPcS83WnRjNUVRClkwcXJKTTNIajlyVEtKeHZtOFg0
            NExDVWI1VStYTE9ISGFRcllTcGhUcTQKLS0tIFdYd2pFeG1UY0ZxUEVuZzA4WXNo
            WGJGN3hxaDV2R1BvTFduSjg4YklTbUkK7uY4ldn0/wIzrTXXgTOXNXiDp2TALaXy
            90JjcAJj7gRGEkHWk846TQ7ZQV+zzCGK8t9CkFR78kBeBnowjw9x/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:54Z"
    mac: ENC[AES256_GCM,data:rkUPcCyS+olfodMqEJLvUW66bttbt4+ZEz1RkXNlhWzrSO1H+uupM2y21qnIfTKWwD+lL+t4ObmK0XSzhfh4fp9T9kRHnSgpYVOuCx7/GriSJ5SHfMfb51x8EyS/C/ONhV0yleIb0SR522FzpVbaWOuwpNWn09Q9dPu8eXRzx/w=,iv:Y55/2iGeZq8lveZXPpAkH1+XWuW6d3xdsqoVcLrcmRU=,tag:3pH3lIlj0cwUOYneFfEp9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
