apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: meeting-automation-staging
type: Opaque
stringData:
    N8N_SECURE_COOKIE: ENC[AES256_GCM,data:Nq8/Dhw=,iv:cY7UblCYSMbGNkzXAFUfJSw1kqkx7VJV/JJIIx+MuTk=,tag:GVUTnPK4tStxMpf4qP1cZw==,type:str]
    #ENC[AES256_GCM,data:yK7CWBT+WdF1j/q8yYimd7V0Omi3mExzxySqRwkwQUV3ryBBARi0Oxs=,iv:mfq98Y8jehYd9QUyflBPJcUQ4eEgGmmFx96Fg2NT+RY=,tag:FbmVdNqjzomqDBaK0221IQ==,type:comment]
    DB_TYPE: ENC[AES256_GCM,data:2i/29fOjox19RA==,iv:VDdGXB23Tcmn87Ut0bgfW8TkeogDNEgBp95JfjZ7iYo=,tag:XsFdbDMz3Vo1f/cWM14zEw==,type:str]
    DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:+PizHk38Z9Id5FiutnWfxW3STRh+Qr3UYxyOZPtZU95jlgl72mjnlX/QGdBvftJMHGbHdK8DLZzIVg==,iv:8/OtwRJoT/CdPcCo6lwlE1MtNRaoSFEipXIvEDHqC0w=,tag:L1cpfkJbNNckDV4shXk2LA==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:hMf3sw==,iv:2WEWF1xHmdHpkHbC1Tl+J/7sADPMBIa2UVgQw+Gn/5k=,tag:+t6b4qyHXNQ89JTvt6VNUA==,type:str]
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:Qo0VJYZkjji7UvjWP8HqcZo/,iv:a+73VQOBe0XLpizIYB2UQ8Kujn6MEpmmjnxG4qq43JY=,tag:aiB8rpOU7lOVJ0REQ+p3rQ==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:oDyUhlRWLyfifbHa,iv:GgUCFCpVPA/NnZh7KLjYEypVUYNMeL73g95G0QVp3PY=,tag:Bfum1NPOQwtgD4AC8jhwKg==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:x4wTBBdjPb2e9LP4l8v3Bw==,iv:zeBhBK+bcL3gCrnbG1JRjxZRTJjAX7qX7He4EgJswzc=,tag:hkY1fDUGfzufNf84Gf1BvQ==,type:str]
    N8N_HOST: ENC[AES256_GCM,data:HR1xXbj3ij1PtbBxeKJEpgaeb/7xojRV3S1Bhigr7tICRnkCQYwzv+l/fThdGNQO38RDgQU3+Ow=,iv:pIwgd0ZUrO+0Lk72FsTEzEybBrBQ45h84lM4bdAUefM=,tag:FYLIR9G/54Mo4n9CPsodBQ==,type:str]
    N8N_PORT: ENC[AES256_GCM,data:ohGyNA==,iv:+PoiglMjpXJaRbt2Fx5AoTx7n/oW2aJpJ+QRAWFykao=,tag:bQQ5ySHFw2zLQBOez6sS4A==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:JcrU0ue2BD3VTIPHz0Uua1thPCcblIo=,iv:6KA31NTLKYcojFrMz6+ERoUcwVaoe8TZyFNS7006LmM=,tag:MqzeUSelC/3IHk6nTdbX8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WVlTck1GT1MxbHNJRzVW
            TE9ZSTZxdjZnVXZxNk9sc1BidDVCRURhYlc4CjhOZjFBWjJFMXVqVXd6MjJia2ZG
            Q0JnZjhUMS9seWRGMGZmSnlTRTVKb00KLS0tIDhGUXp5eTV1azVsVzRvem1vUk8w
            dXJrQjZGWVVUMm5oamNxSEpKVzVjNFkKyZW9zThJr1huaqwegRCz7o5Jba+tZxE6
            bAw/D73JntUUAQSrEQZ1SCiq+owqWHCvWL6NZ93GdORF7jrrmbT9jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:55Z"
    mac: ENC[AES256_GCM,data:972akhlLC7INm8nl1bM9JNBWY3wkRf0lH/YuSpHQjoT+8LDY1UiSw93K/ug3dEShdlYva+HevepHQbLq5qhvBbb6zp8VD+iQpgDSRKvC9dzbERQ+L+eRD33eeGe/cM1v0EcPfMaxlgePAf32km6m7fezjs9Bdav6F0PMktZjwhw=,iv:CusLQ0O4ytbcdEoe/knSGPuff9OeM9Gg6vBxKxDILdM=,tag:Z0sQechSaZ1bYr6GJOjElw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
