apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-secrets
  namespace: meeting-automation-staging
  labels:
    app: onlyoffice-staging
type: Opaque
stringData:
  jwt-secret: "staging-onlyoffice-secret-jwt-key-2026"
  secure-link-secret: "gy3MA8R33ojtIGfXYq37"
