apiVersion: v1
kind: Secret
metadata:
    name: onlyoffice-secrets
    namespace: meeting-automation-staging
    labels:
        app: onlyoffice-staging
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:HNilN/k4VOECXNticzFQBhdShzYiizmNoMCeo5HI9x3y0Tyoz+8=,iv:LP8esdWvVwszZZMOMfBfnK1QFQ4iUKCuj5RDhNwo2o0=,tag:8e6i/TsM1+R5z9YH2Nt8kg==,type:str]
    secure-link-secret: ENC[AES256_GCM,data:6qusZ7S5K2Qw18/OKQ7EP59X2TE=,iv:JYQf71SgSMqmexXNdU11j6B+crZP2NSz64q6HkDp3wg=,tag:VodbQGcpx/QHh5xp4WFOzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeUMyN3pzTGQ3S0xsQVVM
            TVhsWGZodHREakJYems1Y1FVYVViQ0tIZUJVCmd5M1hyRnNrWGwvNGVLUHVRdUhB
            TmNHck11QjE1Nm5IK2Riejd4eVBNZ2MKLS0tIFNWUnJOWDRlcU5qdlEzbVkvUUg3
            WGtMUmZsNFJkaUdYQ24xcW1lVlRCejQKRCS3OOhHE8uon61jcWJfMSG9HKYW/p/6
            M4KW/tnZHcOdRsikZsIkJZqCcm5D9SRqRm9RyTkKn/UisAnHNtD+Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:55Z"
    mac: ENC[AES256_GCM,data:Oc6xhds3tx+XxB0ePF2MUbPhqngHT5znRUlyDxFb+9OGOkEOehMhd/Lg+VnfhTDtcvisu+JNZ3uZ5/PrkfkhU0hwkrBWKFgyKdu1XXyxetnmOIZFL94F4jqAw2h0XrVypgfiUG3/vUeGECzL5Bt86r9eVdPs94+1xFtEn455v/Y=,iv:c1xvKQX+QAg+34lIHle0fNv54DmToruR5MT6CeJ5JdY=,tag:ZCRmm83eGGTG+TcL8VUI0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
