---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: meeting-automation-staging
type: Opaque
stringData:
  POSTGRES_USER: meeting_user
  POSTGRES_PASSWORD: meeting_password
  POSTGRES_DB: meeting_db_staging
