apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: meeting-automation-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:bJdA4nMdPAb9JRrV,iv:Sg1x6iAFTWgmwODLbdw5BgiDe7pVjNAXMgY5NjerHLc=,tag:SilB06cxhqmxk52pPYhARw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DtLLrNj1zwLFaSQ/3UplBw==,iv:tuNqojyEOrWSD22eylizB3S52R1UFhaD3qNI3LQSE+I=,tag:y8McqyuXxAW3d+ZvT3U/uw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:2netuat9kNC69SJgTQAN8KSE,iv:zPNSma47bFERIk06UiVzKUh/fAbJ70LaLo4ZSpYf3rs=,tag:vA6SniOWsv4u5z8+Oqv0KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMzJnbmFRTWtmZzFDSkp5
            Q3JTZVN5K01SdjlzeFR0MXFaMVpwQ3Jld3hnCkxBOWczNkxKelFwdFhuYnhmeHNw
            aWN3Y2V6VmNMNmRBKzU5anhocHptWE0KLS0tIEtQZ3VGSEUwWEluY25iSjNXRThT
            MllkWFdEamN2S1BrMXcxRjZkVFIyR1EKz5MmSD0vBqniwy6Le8JqBXODlZ1nWdv9
            R4BZF72fdqL6OAg2WZHYEKewEma6jQnKnlaWkDnZYbCsn5lurLnyRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:55Z"
    mac: ENC[AES256_GCM,data:Ilxt+ViQOe1S7UyrO1ceB3fRI4GuFHmUBaBhf4L78/ntSOks+mT/9zZUgKEMJZWaDflZZAgZfto1/mwqJb8r+bssLg2YbK7oauc40hvls6qUfPkpndxYgKnvsU9WTL+yGKkb8sB42Sj/WyVprAfo0dhlVqlivbc9hRcImfiItnw=,iv:MpzvPdVPUEjMguYEZmfExPUyPjaUcXrlLUTKQ9/4ESM=,tag:Fds4FIH4HIl5DL9NcMosCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
