apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-secrets
    namespace: meeting-automation-staging
type: Opaque
stringData:
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:E+foMyvvss+IdbM=,iv:5V57C8wJ6yoqro0x7D1Jz9TSYLyVAikzgMuOfHCGKxM=,tag:roLakgIUXrrBBLfI8bngXw==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:BsLMMhx5q+Eb8WgwC/Vy,iv:xhKw4If7OzzYHVdqdcnJ/RsESWDePTEjVDcv12jRS+4=,tag:fWjmAX3nLcNGL38zNrugXQ==,type:str]
    RABBITMQ_ERLANG_COOKIE: ENC[AES256_GCM,data:MVxuufRIpDLXlmspmGbMPbnLpJ8j,iv:dXNObAQna/+kiqdPmZm9yuXYwUxT8iqENZhPwRcra3o=,tag:BppwNxbU+Ji31ZDZOzu7aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeFp6YSt1bWZZanpQbUpL
            ckFMdlRWdjlzMjNTZXh5dlBOM3BFTkJwOEVNCmZZN2YyWEF1VGpETkxWQTN0YzBt
            d2ZJWmx4RGpjbCtWcmpRR2hpY1FpWmMKLS0tIEFCRHlFeS95U29HKytPMnhtMnRF
            bzBITFF5Z2hyZVVRU1RhRDJFMXBSVUkKVNg1TOS8TrTNvXbIhpwKJOoXRNuYTTwY
            dCOcL+svkSqQq0l5gyhQefSWrOXEOp/oqhfDMAvXbNpFAwb6NXX1CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:55Z"
    mac: ENC[AES256_GCM,data:fTDD2bIOzlshUnBm65XIRLzqw/YxckwcP2AhbzKJZGZb1aVe3ghpEQ/Pb8WfDLRm2PHTBy2zGNM9ZvZhVtLNJRLPTTA0CtGHYKzHpNmUW/i/M6n35tYzq0DOUnbiI1+kLqrrpaipBFPhPyS4XAqryJKOeD1uWTgM0zuaWVqIGbI=,iv:PI5+wnUuu+KrvoDmIqgG9HR2TlT22uEUAM2fJWQPL14=,tag:y3mc+0Lg/S2SAGqoXPodGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
