apiVersion: v1
kind: Secret
metadata:
    name: redis-secrets
    namespace: meeting-automation-staging
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:R5epYKycWAtIun0Sx98=,iv:9S96V6CyI+Woz2JhlUDeB4wuKI3Y6okzH3LyZz5TuSo=,tag:kQy0/mwT0NGCL7jYrzFMWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWEZubWFSL2YrMkc3d2VR
            QnpqdVFGOHg3a0JsMDdIQnVMdDZRRmQ4T1FzClFOVE1xOTFGRjBhK0crbXFFUUlr
            ZDV2cElSeTNKMDZ3NmpIL0JVbFUyOHMKLS0tIHMwVXJxRkZzWE4zeGZNcEo0ODc1
            NG5Tb0dmUzhHU2FncHJlUmd4VkIvaTAK/tj8SOvwL8s2FnyGrJChOQdN/7r+/T1c
            XLrSPtXsoqtEmed40RpegtxCDhnlRuFltCW82zO0n5+pqCvH3733rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T16:17:55Z"
    mac: ENC[AES256_GCM,data:q/DwmxVbLdDQ/U8b6lKBhtskcF0LTw9yvi+zzVDfuCbJdH9rRRq1nTs52ppjIxw7rdYoXf/wNnMkFCyyQ9ABJDmln60S1x9s+eqQkIV5VINi/ip9mNmNgzxd8jaZLlrafFZJgVl3wKpJOi2TSouII4/21d6tJFkOCkBRcu28W5Y=,iv:4R12LwR/uqZZjhVLBhMz/cL6LIMhlKQ4JFeESzhdG/w=,tag:e6D8xhnAiA8q/cPDqCC0rQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
