apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-models-claim
  namespace: meeting-automation-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
