import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

@pytest.mark.asyncio
async def test_branding_endpoints(client: AsyncClient, db_session: AsyncSession):
    # 1. GET branding (should return default empty config if not set)
    response = await client.get("/api/v1/settings/branding")
    assert response.status_code == 200
    data = response.json()
    assert data["id"] == "default"
    assert data["is_active"] == True
    
    # 2. POST branding (configure custom settings)
    custom_branding = {
        "organization_name": "Tunisia Tech Corp",
        "logo_url": "https://example.com/logo.png",
        "header_text": "Confidential - Tunisia Tech Corp",
        "footer_text": "Generated by Meeting Automation",
        "default_watermark": True
    }
    post_response = await client.post("/api/v1/settings/branding", json=custom_branding)
    assert post_response.status_code == 200
    post_data = post_response.json()
    assert post_data["organization_name"] == "Tunisia Tech Corp"
    assert post_data["id"] != "default"
    
    # 3. GET branding again (should now return the custom config)
    get_response = await client.get("/api/v1/settings/branding")
    assert get_response.status_code == 200
    get_data = get_response.json()
    assert get_data["logo_url"] == "https://example.com/logo.png"
    assert get_data["default_watermark"] == True
