import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

@pytest.mark.asyncio
async def test_branding_endpoints(client: AsyncClient, db_session: AsyncSession):
    response = await client.get("/api/v1/settings/branding")
    assert response.status_code == 200
    data = response.json()
    assert data["id"] is not None
    assert data["is_active"] == True
    
    custom_branding = {
        "organization_name": "Tunisia Tech Corp",
        "logo_url": "https://example.com/logo.png",
        "header_text": "Confidential - Tunisia Tech Corp",
        "footer_text": "Generated by Meeting Automation",
        "default_watermark": True
    }
    post_response = await client.post("/api/v1/settings/branding", json=custom_branding)
    assert post_response.status_code in [200, 409]
    
    get_response = await client.get("/api/v1/settings/branding")
    assert get_response.status_code == 200
    get_data = get_response.json()
    assert get_data["logo_url"] in ["https://example.com/logo.png", data.get("logo_url", "")]
    assert get_data["default_watermark"] == True
