apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-server
  namespace: meeting-automation
  labels:
    app.kubernetes.io/name: livekit-server
    app.kubernetes.io/managed-by: kubectl
data:
  config.yaml: |
    keys:
      prod-9a4ac9f989143b65: prod-8f8b7b429f01180c89e03a1b30eeec4be871c0fa184c823a
    log_level: info
    port: 7880
    redis:
      address: redis.meeting-automation.svc.cluster.local:6379
      db: 0
      password: flgyEhZKHVyMBge1QkdKtA
    room:
      departure_timeout: 60
      empty_timeout: 600
      max_participants: 10
    rtc:
      allow_tcp_fallback: true
      force_tcp: false
      ping_interval: 5
      ping_timeout: 60
      port_range_end: 60000
      port_range_start: 50000
      tcp_fallback_rtt_threshold: 0
      tcp_port: 7881
      use_external_ip: true
    turn:
      enabled: false
      loadBalancerAnnotations: {}
    webhook:
      api_key: prod-9a4ac9f989143b65
      secret: prod-8f8b7b429f01180c89e03a1b30eeec4be871c0fa184c823a
      urls:
      - http://backend.meeting-automation.svc.cluster.local:8000/api/v1/livekit/webhooks
