apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: livekit-egress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: egress
    app.kubernetes.io/version: v1.8.4
    helm.sh/chart: egress-1.8.4
  name: livekit-egress
  namespace: meeting-automation
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: livekit-egress
      app.kubernetes.io/name: egress
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: c2812c546fc681e3eb31f22cfc88ca7da42b632f109034732cdbd9fd443f2e0f
        kubectl.kubernetes.io/restartedAt: '2026-09-11T12:50:34+02:00'
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: 'false'
      labels:
        app.kubernetes.io/instance: livekit-egress
        app.kubernetes.io/name: egress
    spec:
      containers:
      - env:
        - name: EGRESS_CONFIG_BODY
          valueFrom:
            configMapKeyRef:
              key: config.yaml
              name: livekit-egress
        image: livekit/egress:v1.9.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: egress
        ports:
        - containerPort: 7000
          name: health
          protocol: TCP
        - containerPort: 7002
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
      - name: dockerhub-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 3600
