apiVersion: v1
kind: Secret
metadata:
  name: livekit-secrets
  namespace: meeting-automation
type: Opaque
stringData:
  LIVEKIT_API_KEY: "prod-9a4ac9f989143b65"
  LIVEKIT_API_SECRET: "prod-8f8b7b429f01180c89e03a1b30eeec4be871c0fa184c823a"
