---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: meeting-automation
type: Opaque
stringData:
  username: meeting_user
  password: "ODUzYvZ1hxrcZauvvl1k6s5wH8r8I"
  POSTGRES_USER: meeting_user
  POSTGRES_PASSWORD: "ODUzYvZ1hxrcZauvvl1k6s5wH8r8I"
  POSTGRES_DB: meeting_db
