---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: meeting-automation
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: "EyftwTfJsJf5448aiLj4g"
  RABBITMQ_ERLANG_COOKIE: "prod_meeting_cookie_2026"
