# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template for migration file names, e.g. "alembic/versions/93246875418_add_a_column.py"
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the 'pytz' package.
# If null, the local timezone is used.
# timezone =

# title for the project, created by the init command
# project_title =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'check' workflow, diligent reality-checking
# will be run on the database connection setup.
# 'false' prevents connection errors from being raised
# when the database is not available, allowing for
# the 'check' workflow to be used without a database.
# check_for_existing_database_connection = true

# revision rendering arguments, used by alembic revision --autogenerate
# and alembic revision
# revision_environment = false

# don't require transactional DDL
# transactional_ddl = false

# sqlalchemy.url = driver://user:pass@host/db
sqlalchemy.url = postgresql+asyncpg://user:password@localhost/meeting_db

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S