# Suppress deprecation warnings to clean up logs (explicitly permitting them for now to ensure compatibility with Celery/Kombu)
deprecated_features.permit.management_metrics_collection = true
deprecated_features.permit.transient_nonexcl_queues = true
deprecated_features.permit.global_qos = true

# Increase memory high watermark to 60% of available RAM (since container limit is raised)
vm_memory_high_watermark.relative = 0.6
