"""add_status_to_recordings

Revision ID: 1a7898e785eb
Revises: f48da7263722
Create Date: 2026-02-25 23:05:54.037573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7898e785eb'
down_revision: Union[str, None] = 'f48da7263722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'status')
    # ### end Alembic commands ###