"""add team members and meeting rooms

Revision ID: 4fb76575fee0
Revises: 0ec3faaa42b1
Create Date: 2026-03-24 01:49:46.978835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb76575fee0'
down_revision: Union[str, None] = '0ec3faaa42b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_rooms_client_id'), 'meeting_rooms', ['client_id'], unique=False)
    op.create_index(op.f('ix_meeting_rooms_id'), 'meeting_rooms', ['id'], unique=False)
    op.alter_column('action_suggestions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.add_column('meetings', sa.Column('room_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'meeting_rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'room_id')
    op.alter_column('action_suggestions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_index(op.f('ix_meeting_rooms_id'), table_name='meeting_rooms')
    op.drop_index(op.f('ix_meeting_rooms_client_id'), table_name='meeting_rooms')
    op.drop_table('meeting_rooms')
    # ### end Alembic commands ###