"""add_client_to_user

Revision ID: 6c350995e07f
Revises: fe909ed38c52
Create Date: 2026-03-20 10:42:07.135314

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c350995e07f'
down_revision: Union[str, None] = 'fe909ed38c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add client_id column as nullable first to avoid errors with existing data
    op.add_column('users', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_users_client_id', 'users', 'clients', ['client_id'], ['id'], ondelete='CASCADE')

    # Data Migration: Create a default client if it doesn't exist and associate all users with it.
    conn = op.get_bind()
    default_client_id_result = conn.execute(sa.text("SELECT id FROM clients WHERE company_name = 'Default Client'")).scalar_one_or_none()

    if default_client_id_result:
        default_client_id = default_client_id_result
    else:
        default_client_id = str(uuid.uuid4())
        op.execute(
            f"INSERT INTO clients (id, company_name, subscription_plan, subscription_status) "
            f"VALUES ('{default_client_id}', 'Default Client', 'ENTREPRISE', 'ACTIVE')"
        )

    op.execute(f"UPDATE users SET client_id = '{default_client_id}' WHERE client_id IS NULL")

    # Now, alter the column to be non-nullable
    op.alter_column('users', 'client_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_client_id', 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###
