"""add_stripe_ids_to_clients

Revision ID: 8779f409105a
Revises: g1h2i3j4k5l6
Create Date: 2026-06-21 19:47:39.671695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8779f409105a'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_action_assignments_action_id', table_name='action_assignments')
    op.drop_index('ix_audit_logs_client_timestamp', table_name='audit_logs')
    op.add_column('clients', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.drop_index('ix_meetings_deleted_at', table_name='meetings')
    op.drop_index('ix_meetings_start_time', table_name='meetings')
    op.drop_index('ix_meetings_status', table_name='meetings')
    op.drop_index('ix_participants_meeting_id', table_name='participants')
    op.drop_index('ix_pv_sections_pv_id', table_name='pv_sections')
    op.drop_index('ix_pv_versions_pv_id', table_name='pv_versions')
    op.drop_index('ix_recordings_egress_id', table_name='recordings')
    op.drop_index('ix_speakers_meeting_id', table_name='speakers')
    op.drop_index('ix_transcription_segments_transcription_id', table_name='transcription_segments')
    op.drop_index('ix_transcriptions_meeting_id', table_name='transcriptions')
    op.drop_index('ix_users_client_id', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_client_id', 'users', ['client_id'], unique=False)
    op.create_index('ix_transcriptions_meeting_id', 'transcriptions', ['meeting_id'], unique=False)
    op.create_index('ix_transcription_segments_transcription_id', 'transcription_segments', ['transcription_id'], unique=False)
    op.create_index('ix_speakers_meeting_id', 'speakers', ['meeting_id'], unique=False)
    op.create_index('ix_recordings_egress_id', 'recordings', ['egress_id'], unique=False)
    op.create_index('ix_pv_versions_pv_id', 'pv_versions', ['pv_id'], unique=False)
    op.create_index('ix_pv_sections_pv_id', 'pv_sections', ['pv_id'], unique=False)
    op.create_index('ix_participants_meeting_id', 'participants', ['meeting_id'], unique=False)
    op.create_index('ix_meetings_status', 'meetings', ['status'], unique=False)
    op.create_index('ix_meetings_start_time', 'meetings', ['start_time'], unique=False)
    op.create_index('ix_meetings_deleted_at', 'meetings', ['deleted_at'], unique=False)
    op.drop_column('clients', 'stripe_customer_id')
    op.drop_column('clients', 'stripe_subscription_id')
    op.create_index('ix_audit_logs_client_timestamp', 'audit_logs', ['client_id', 'timestamp'], unique=False)
    op.create_index('ix_action_assignments_action_id', 'action_assignments', ['action_id'], unique=False)
    # ### end Alembic commands ###