"""Add client_id to core entities

Revision ID: a62045bbe49e
Revises: 6c350995e07f
Create Date: 2026-03-21 02:08:52.174630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62045bbe49e'
down_revision: Union[str, None] = '6c350995e07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_suggestions', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_action_suggestions_client_id'), 'action_suggestions', ['client_id'], unique=False)
    op.create_foreign_key(None, 'action_suggestions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('actions', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_actions_client_id'), 'actions', ['client_id'], unique=False)
    op.create_foreign_key(None, 'actions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('audit_logs', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_audit_logs_client_id'), 'audit_logs', ['client_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('branding_settings', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_branding_settings_client_id'), 'branding_settings', ['client_id'], unique=True)
    op.create_foreign_key(None, 'branding_settings', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
               
    op.add_column('meetings', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_meetings_client_id'), 'meetings', ['client_id'], unique=False)
    op.create_foreign_key(None, 'meetings', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('pvs', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_pvs_client_id'), 'pvs', ['client_id'], unique=False)
    op.create_foreign_key(None, 'pvs', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('recordings', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_recordings_client_id'), 'recordings', ['client_id'], unique=False)
    op.create_foreign_key(None, 'recordings', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('transcriptions', sa.Column('client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_transcriptions_client_id'), 'transcriptions', ['client_id'], unique=False)
    op.create_foreign_key(None, 'transcriptions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.drop_index(op.f('ix_transcriptions_client_id'), table_name='transcriptions')
    op.drop_column('transcriptions', 'client_id')
    
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_index(op.f('ix_recordings_client_id'), table_name='recordings')
    op.drop_column('recordings', 'client_id')
    
    op.drop_constraint(None, 'pvs', type_='foreignkey')
    op.drop_index(op.f('ix_pvs_client_id'), table_name='pvs')
    op.drop_column('pvs', 'client_id')
    
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_index(op.f('ix_meetings_client_id'), table_name='meetings')
    op.drop_column('meetings', 'client_id')
    
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
               
    op.drop_constraint(None, 'branding_settings', type_='foreignkey')
    op.drop_index(op.f('ix_branding_settings_client_id'), table_name='branding_settings')
    op.drop_column('branding_settings', 'client_id')
    
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_client_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'client_id')
    
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_client_id'), table_name='actions')
    op.drop_column('actions', 'client_id')
    
    op.drop_constraint(None, 'action_suggestions', type_='foreignkey')
    op.drop_index(op.f('ix_action_suggestions_client_id'), table_name='action_suggestions')
    op.drop_column('action_suggestions', 'client_id')
    # ### end Alembic commands ###