"""Add billing and usage models

Revision ID: ab93febdb189
Revises: a62045bbe49e
Create Date: 2026-03-21 04:10:43.767240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab93febdb189'
down_revision: Union[str, None] = 'a62045bbe49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'FAILED', 'CANCELLED', name='facturestatus'), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('invoice_pdf_url', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_client_id'), 'factures', ['client_id'], unique=False)
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_index(op.f('ix_factures_stripe_invoice_id'), 'factures', ['stripe_invoice_id'], unique=False)
    
    op.create_table('usage_minutes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_minutes_client_id'), 'usage_minutes', ['client_id'], unique=False)
    op.create_index(op.f('ix_usage_minutes_id'), 'usage_minutes', ['id'], unique=False)
    op.create_index(op.f('ix_usage_minutes_period'), 'usage_minutes', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_minutes_period'), table_name='usage_minutes')
    op.drop_index(op.f('ix_usage_minutes_id'), table_name='usage_minutes')
    op.drop_index(op.f('ix_usage_minutes_client_id'), table_name='usage_minutes')
    op.drop_table('usage_minutes')
    op.drop_index(op.f('ix_factures_stripe_invoice_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_client_id'), table_name='factures')
    op.drop_table('factures')
    # ### end Alembic commands ###
