"""create_clients_table

Revision ID: fe909ed38c52
Revises: e9dd04c9d6f1
Create Date: 2026-03-20 10:34:33.199604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe909ed38c52'
down_revision: Union[str, None] = 'e9dd04c9d6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('subscription_plan', sa.Enum('GRATUIT', 'PRO', 'ENTREPRISE', name='subscriptionplan'), nullable=True),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'DISABLED', 'PENDING', name='subscriptionstatus'), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='billingcycle'), nullable=True),
    sa.Column('minutes_included', sa.Integer(), nullable=True),
    sa.Column('minutes_used', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'TRANSFER', 'CASH', name='paymentmethod'), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.alter_column('action_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('actions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='actionstatus'),
               nullable=False)
    op.alter_column('actions', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agendas', 'meeting_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agendas', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agendas', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('branding_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='meetingstatus'),
               nullable=False)
    op.alter_column('meetings', 'creator_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('participants', 'meeting_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pv_sections', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('pv_versions_created_by_id_fkey', 'pv_versions', type_='foreignkey')
    op.create_foreign_key(None, 'pv_versions', 'users', ['created_by_id'], ['id'])
    op.alter_column('pvs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pvs', 'is_validated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pvs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recordings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recordings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recordings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recordings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pvs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pvs', 'is_validated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pvs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'pv_versions', type_='foreignkey')
    op.create_foreign_key('pv_versions_created_by_id_fkey', 'pv_versions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('pv_sections', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'meeting_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'creator_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meetings', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='meetingstatus'),
               nullable=True)
    op.alter_column('branding_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agendas', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agendas', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agendas', 'meeting_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('actions', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='actionstatus'),
               nullable=True)
    op.alter_column('action_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('clients')
    # ### end Alembic commands ###