apiVersion: ENC[AES256_GCM,data:FUI=,iv:jUyyx11Ohp1xWOzamwpXTH7yFjlJRrrFwBzsLcaLthI=,tag:gJUCm1gFNxj/1KEyrtQ8fA==,type:str]
kind: ENC[AES256_GCM,data:acWU9WwB,iv:M14NjwcN/3Zl0BCDK1of4LPsXPSZ6VR3bjGQgVhiRck=,tag:kJFlkM/nwc6GTm7w1/ivBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NXUx6vkl50XvunQGnxeu,iv:1fv+Foohy+jYJmoBy0VBGKlTy7rgfEOIYIIk+ELNuXI=,tag:sAqaO0tH8Wocn+1T0O+H6A==,type:str]
    namespace: ENC[AES256_GCM,data:Uc15reVd39rIVleqf8Ge7ByC,iv:BJcGup7UL6GGZ06ZlGpmw24UEqiDoe8nTvRVnEFOWO8=,tag:sFaqVQSpYLpDbVWkkLyayA==,type:str]
type: ENC[AES256_GCM,data:okK/0JOj,iv:t33/uSLA5BCSNjlNTmuh7J4yCFpyAoZjS8AXYK+KeLc=,tag:KaxF1DHyJTSCm/TEXa99aw==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:IoZ2FRfb4CgJlMbA4EmqA0Q/xv7kSjTXtKcEkFCXswNI0SIloEdDO24Yjf0zR14/02cxwuny6MC4Ts85CV0r0J6EotDOr/YlmjZc,iv:jGH4VLGzoHwxL/HVYlSftwAFraaVJngH+rMuUYAZlS0=,tag:DHHSyF1VDG8ka/yNHslvPw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:v7GlxbnKkI7auSNCwwt7oksRqGP9O1yLPXkZLQl2CR9VC2dL6Op+dKlpSA==,iv:Xb3bxJTA6aZyy/m6IvoCuVabN1HwVQEzLJA2PKWsp18=,tag:98KhFAA2n9aLvxuO8oFp7Q==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:gDFO4ev7/OEEn9PgFdXL0D3dc4cdUl2lOyXmtVp05pBXuDNk2bx2N891LwDWDhPB/HhNiOTKsMgO3WUoTmdK7gz4,iv:oh9A5u6Yf5LHJ7vVwIp3y+1wRzKHP5HWXLiOeHpZAAQ=,tag:hvF1H8T3pZ4xL4/aQZnazg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:a9DbcmFPZGbrfw==,iv:VOfYTcsWT7JMWaTM59vJj00fQEIRrkd2PbxiiV8X/y4=,tag:MuRrnsC3OYjqR6KYwfskJA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:8nB3c6izF/Dr5RNdQVI=,iv:tpkOTj1MNuKZJTxJrZURpCqweGkJQ2KlKyqpWzRloz0=,tag:UmD5XU+Q81vmY42UZhi0ww==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:Q8AV5L/vbhegzGl7+kTd5xwWpocJvmpZ/KH8Xx5qnFQ=,iv:D4ZRh0N0eLIcDW29nbRpnI4XJX5b53n/S8DbkwEZP28=,tag:1bsqm3W8J60MpIs9ryPrDg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:kn4vGjrYEf8gIO0gbtxdhU5pVTT9+75fcm3s82y/sOdQJvG8SlorbJZdDFjfnnhj8xR8RHFSOZQqRpw7kTfJEj3+rbSDB0ShIHyp6n1SUyPh7EqstvyO8fKPBW1xKWr57jzB7MWtWF7n8inYcI0Pg9AuOMF+gjXKD2KsR04SLxvTi5MF0blcZAjIJv3JIvnuT0Bn+ezxiskaUgNnSYipz74awHg=,iv:+szFidh3ObFD62PxyO5b+GaMY73UJaqnhq/U5X5PjLc=,tag:GAbtiP1jrwjKyn2kd9/gcw==,type:str]
    GLADIA_API_KEY: ENC[AES256_GCM,data:xulcXAdXTkpYMODcae1MeUNvBdWztLgDUWgHjaIdjdJNa7bO,iv:URsoJ+K5ujMtOv1RVdwOJsXCUC3BGiUPc3zaudpz1EA=,tag:CJ1DeQ5TSyJTNm5awRKk+Q==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ncvxM/RcKDLwrkysL9FZCYtd9rMq,iv:aOwDZO04yom305n2HsG44gK7ywfbyWWKUKDstUJz1R4=,tag:gUf2DaTaZ4zhKrI3G8Bf0g==,type:str]
    WHATSAPP_TOKEN: ENC[AES256_GCM,data:d6u1BqQUV4eEZNPV2UCZIDaVBQ==,iv:HB9OeCV7Df9sXFZ/tmyzAMeKsrO269IYjsOdPA/R1uU=,tag:2A+uODwK5Z1nPvB5F3kvtw==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:MAEZSfjuXsjT4piu1JRMtydxagoZEUK12QZsdFne+RbrNU0yG7l5Cdxm9L0WDV/Qlg==,iv:RXyQb7giiX4n8MOo40fIwpoUMHLChPqXovB1rMzVhhQ=,tag:mpKlfFu8pIRITMTZLjTLGg==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:udeO9dfv++MOfbVo9odfNKnW7o7tmesuy32BViV4Y2hEQTAbVVxptp4fVg==,iv:cQEUJiKwHhm5eY71kAkZ+WFkuMQpsy+P+eA4SyhjgMw=,tag:LWpm2Ogwike1xqNCaEDnRA==,type:str]
    INTERNAL_API_SECRET: ENC[AES256_GCM,data:PHIiwk7RNi7z6rtEtTlp29XBISUNcleavz1Po1jHIeg=,iv:IC3te/2UIlGiH12zlQOhonCN224qVujZTiMJAaymOhc=,tag:rZ/2QRYtmses0cSMziAeEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyrjgyvppvvatk9ngf03mn28wqd0pmx5frq02gmrcms3cz4t5chqwwn0kh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWWRXdTh3SW5WdmF3ODBp
            NEhUSEpwQm5UaXJNY0lPN1h3WlNYWWh1cEVJCjdKYzBIN00ybkVOT2QxT0Qya0xi
            anN6c0VHdWFWTDN1Nzl4L1Z3Qm0yR3MKLS0tIG4yN0ZianVGWTZmSmdDZWR4REUx
            dHJLTEpURzFZbnY5S3daZjNwYWk2bUEKSplCf+NBUd0OjXWZ3OOOhZlWG2mvQOqU
            SIvPXXTlElVjI9mAFNGSsvYtIL4p12E4Da0YbnJv9LuNpE0Saq+uZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T02:46:11Z"
    mac: ENC[AES256_GCM,data:wKncc1zQ9BQbTYSTo+dcjSiLhSnIOnILFNfkDInaDRw05MUQ2zBtGgdHjxuXQqMNSEuSUjBUhwKi8EbRqjUTyun3yKv4SppO8vgC5upx/J6Qa2WWjAjSinAncNtjS+mxJGAm+PfTMoBj80VjGI6aqb8XnAzmdSUUtOTCigUJEng=,iv:v76CnmyFBtAw8usvCmUvc+BqDQDtts58LjdUuicfen4=,tag:JtZOv3Acpw67SFpDTyWU6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
