apiVersion: ENC[AES256_GCM,data:IkQ=,iv:OGAuyfv4WGF9DJgx6XXNDt398wgtMkgB4bfiCo5E4wE=,tag:16CNnzIjDmWZcV6B3OKALg==,type:str]
kind: ENC[AES256_GCM,data:Tp2SZTgh,iv:QsSyv53FWZNK5N9fjEBkiABnIyt/tLAP46kbZ0RIG2o=,tag:NrQ9E0CBvns3E5y+QHpj8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lYjSygOx+klbYmu01+if,iv:JzbnGii7grfg2HXjGqB15e5KLlB8I76/k+gpJ2uFbRk=,tag:E80U4dM2LCJwgNn6Bt03Gw==,type:str]
    namespace: ENC[AES256_GCM,data:FvJeJkHue1qyMWEQevZqDQxI,iv:8892kudOej6JwxlGGYzrijHj8boUsUyzqYwPGdCYokE=,tag:Jschn/pg8vurZ4R+23T6GQ==,type:str]
type: ENC[AES256_GCM,data:p50c7pGE,iv:QFh0KpO2TcOK2rWTrPJZkiYLVJ9OO1tXJjotTIr4QDM=,tag:ZkfndRNGWpJuSJgLoOICTQ==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:K32kOQwWlK5dL/6LEKXShsmosm/v3epI7RXVnhXdXmFj7knjhWdW/7ugghORcJ39dC1E+9akeT/Dh+BENsCMQ19MVB5sKeBtINJY,iv:PqjGfaEkqvXyuUUphrpXfd0hIa23zGiR3fGeYAGlfD4=,tag:WxTbDYgM5YlgM34iHpfdUw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:v1Ec2KnPcJ0/BrrdOGvFoEEelsRV9kirgYoz5rCa69Oqn9VdkRUeQOnu0A==,iv:ciLPq5jiObXn3OsqFrYUq8kscYBe175zeqyIzkWMYd4=,tag:xxAVGfZpcPa2LqqL/koeZA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:XCbUyOIZuhx4RUF2/NxEq6pquU/KSqhwXu6nFVx8TYWNmat7zXkk6ti1/RjmMwGF5EeR8MMJGVZcRh+IMyno3eZG,iv:iAjQK7WwYzOdYTi5Wn+wdGeGzRssz/Vr/gd/gVnjLBQ=,tag:XNlPWYqz9ew2iXcdC4wisw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:aowVu1brplRM5A==,iv:7++6zUtVSx8X0xo16ROJyWsi2vJG8S3aHrvMm3QkMAo=,tag:2pfYJSP+L0S14bhpPggpjQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:PTlnNh2d1g3SfDzlgFY=,iv:8z9Emm1rACGYsfwWb8LD1EMNWPFw6vU9A7f090PEjcg=,tag:frU1kAu060d98nqJrltTXA==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:EQFJlV4/UKaU34s+qUoMUL4ynAz1C9iXqRfKklE6/rA=,iv:/HD1kuFMILwgDj3FfJ6RsYw77N8DHpbVaNyrNtyhUCg=,tag:aUWUEbBZDohLefN2cd3KVw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:tE2mQ7DCYeQsOCGhGjmfUjruPtdEbM8jDCqC3OnJp1VH8Rsco+e2VkVIuBoEGHxvly4h7DPYpAFIB/iQsynpR/hXC1Cg/++sKdSA8plnky6vReJfbAdp8udqrFl/Ks344Bs5ko3UW0EDmYb/0s9q+S7TJwj/yooBnfsPTtVPcts+nIXKs993b2oEvqlBEhZuFObVQ3AmwNwuvOM404DK8jnVsYc=,iv:N+vEnUDNEg69LxMskLKEM5XLHl8JRSHToHTfSDyDeJA=,tag:ULWS6FpD5SYaZO12Ti5uNw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:AE26zbAJY36MD8F6uQyzk/gMlAVF,iv:2ORrwfeTqxvTeGQ9dPQCq7fTp0zGNgusd6kkEF+LFqA=,tag:rRtNPKQc8/NQ2qD++c9lVA==,type:str]
    WHATSAPP_TOKEN: ENC[AES256_GCM,data:xhPvYuCuHm+oVglh/T9w+363XA==,iv:44nrM0FVK2bmIJnsE0t/nB6ogGvZFkZVJVBNZNsRKrA=,tag:i4iy8Rcw8ebddwsTC9v+BQ==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:zhO3Zbaj4QB7tznTUPMDmU1SAPNl4Qwqhds70MmZ/CHukuxPfLrx7Q4Yx5sWUB4ZXA==,iv:Kh7T8AtvlvYlbjdCZ0TpCAvxcC2LGEbKpUaW2KotnQk=,tag:IZo+hsB+PMbXUL/g2xYQ/Q==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:xBR/WOTtFpvDF7VGlpBKylOKUHGMzDYItpLur58MLfrzGvTXc2A02bkOlw==,iv:ggLUjXqnMTRZth7u6FSr4egDfPn9qU4WrToUeUAplaI=,tag:yTGO4/4Cwn9HuWMw7nKw6A==,type:str]
    INTERNAL_API_SECRET: ENC[AES256_GCM,data:xrn6CnrgIxCHdrWv0T5ZcMAajKnUuvmA9z01U7HPFRw=,iv:z45XBiOlEv+zF69bhqcE4N1AsMsPt5yWkkKf195BplE=,tag:ft77AOydMZA14vRQrbw1BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyrjgyvppvvatk9ngf03mn28wqd0pmx5frq02gmrcms3cz4t5chqwwn0kh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanFyU2x1cURHNDYvaWdM
            WjFRUmt5REJtdWFjeG1ZWDRpaFRkbHIyaUQwCjNRWlJkOGRKd29KdGNrUFRnMzZO
            OXBFYiswZDB0VEVmaDF4WVpTeTJUdEEKLS0tIHFLQ3FGa3V1RXZ3WFo5YzlhZGtV
            UlJvTTFIYVVGOEFPcFd4dUovWjF5ODAKE/f8BGVqtR9IiYSuHLhADckH7T2KYAsj
            N5WvPQHftxwLPt1R7B1qg4KslT+XuNvOamp0L8rsfl7trrEzYPbOFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:28:44Z"
    mac: ENC[AES256_GCM,data:j5yV1pGDDxAZk5ghvSGZXIujjDd1+2Sa6A4hovm2v5Qe1T5DCSn6P87Rc0jZ4LhlXegoxk8GiDn/kHcH61NmRhfITmvA90i2mRTam+89DJ8VBg1+8cpa0idqUcXCb0a61jjyD2cVvM1V+nnmzKa3YpCfueinhSTY3qvR8eCFpk4=,iv:m/jL9DZYIL1hxhuCxneIbJUsETANqpvQin/xR8l8h4Q=,tag:M9Yj0nJYTVt/QKHBa8Ndkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
