apiVersion: ENC[AES256_GCM,data:Wxs=,iv:T9NaOwX3+2fVyaMA9mINrEAwGbwZx9f6hXNaptfSpzc=,tag:7ZJzljOj8JA0ueuSVkvV5A==,type:str]
kind: ENC[AES256_GCM,data:DEWLQB+m,iv:5FnD65eWrUzEelne8VHQbMB/kEr8U0UwG0r3ngoTD4U=,tag:1TKAGzNvHLycpbQkfkSrTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GcL6elvzNtx0cejSlZ7t,iv:eBmoS/8cyLP+qU/ia0Jr7ZicSgYOKU7FMDGeEFYsWY4=,tag:DMU652BCs/vWlcqOtaR8lw==,type:str]
    namespace: ENC[AES256_GCM,data:/5YFmsV9y3WqnF1iqkFrtowK,iv:A2GIhwZexgp+QEuww/xmgUz32Ml66avPq7oNN9JtihI=,tag:J9fgr4pZsNtCNz7/+lEADw==,type:str]
type: ENC[AES256_GCM,data:eU8SOc5V,iv:U649M0H3ul6kgtN/610zVnGAIranFQ8hyieVgqq90pE=,tag:ibutCRrWPVCVVzzmAr6CVg==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:sNCrTXxCD9mLEVnT8Avu2KBJQ3Xo4aGmEYsMfCPYfoj/+T1Ngl97loPsojydPnTf5FXTYYnASDA6yWz6mgRo0wwdxkYE+ecBwv08bgdTJAg=,iv:UQfwwhjWy65TJGjQxHYpAHjxH581W5bQ+QgFS1W7ZMU=,tag:DxmuiOe69gcPixuo96NFNw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:FSLJxgzKBm2A381yv8hEzdK8CmMm62IPxHe7ktskzMF2aTX70s373kQ=,iv:rdySDDvSOt94eIBbmFPqwDESxUiybAxKUI49gGCBrUE=,tag:uelEw99CN3fGdj3vxlmAWQ==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:FxHkkXhfP1W/GK2ImuKpNXhCLmoRTFINv5fbTQWn3rWUCX8EFUDNFPLwtse7WWedqDOmzLiOeg==,iv:ML3jR+V3PZOxYVja+hWnQ04p+u05vEpZREDCy5etx3U=,tag:TXdlDTxayAS93m7Z7K2Mqg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:0akxfoG7oddmCs1H1sUn7LUONcri4pVi8DnV4zRbBGHZNzJTEPbYRBifUyNojw==,iv:es5GvsH5KoAcUHRq17arz/q0UaGAoHA1TjD1lxuodHg=,tag:YzRyX9BV7Rrb97mjWypN5w==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:dPHF98zsfvo9Qw==,iv:8qvI7Zh1bXfSNBwPg6wO/rcvgzEoA0jYgzaWA9WgoHw=,tag:LLfO3xxj+zwLNSX5ceOS+g==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:eRPJ6wUA3f5iKp93beYdoO1BJQ==,iv:0Xy1khq9eZc5hAnWcKfcdLbvsfwI6VqKnUNH/fXVyjQ=,tag:2VHfGfEkpPXb6+uzcmD8SQ==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:1nAYiHOgikQ89mK/ZEBx++Vdf7oGJqghWQ==,iv:CU4l8Hjw8b9j1lnvGg/BaF7jhCD9WwO9Z6ajxdPKPns=,tag:03SsUoQeAOMU86N1v/BIKg==,type:str]
    GLADIA_API_KEY: ENC[AES256_GCM,data:VCjOST9an8pxYXjQ+Pgnom9bHm6OMopN,iv:jJpb3XaCQBTJ0cF2NX30lG/G8aNBTGjoWq+dr5hAFOE=,tag:GpVb84iY1DO5ayNt+lilHQ==,type:str]
    ONLYOFFICE_SECRET: ENC[AES256_GCM,data:nfjPpXzm5q/LOOg1eDKfglLgAVnvCOzwFXcT,iv:/gsVeqeXeEngyJTeVsIxjs2FUePbio+64+eIl9z7LgI=,tag:cicQCrLO4jz8u48juB0qKw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Y8UKKLcIQfKRayNyHW9klG7p98qvDXI4,iv:pIeJ+817qw5ixcPyBGXKzYTLiAp9JvKtTjR7EfeNd/A=,tag:RnPJvPMIIWea/wU8EJyMRQ==,type:str]
    TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:BIrFR9pOvoS2GXhm4NPbr4dLkAJ/yhdm6gEv3eY=,iv:hpkOZiI8r7hn17vGncssSBjLac4DyrL7UTzwOfQDqJY=,tag:NGy6Xmqz9sYSOs5AGhuJZA==,type:str]
    INTERNAL_API_SECRET: ENC[AES256_GCM,data:qAtj22erkHk8so/daLaOPvB/Ple46g0yv3kQEpc=,iv:kUOQC1D+vJMo2F32Fu5CPZX6BAM4pU7ojM45XZfL5C8=,tag:aABDofo9niLF2IxlM17gAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bngycnJpanlyVHdxaE52
            TlZCcDBIRkpVMElMcXhNK3NBMFl5L1N5K3hVCjQrTzBGbXczZWVicSsrVEJsOGN0
            cDdjZW5Ea3lwTm1FY0hRUk1DdmE0L0UKLS0tIDcwMEVCYTEzYmJkYUtnd1N4Ylkw
            TStkV3NuYTBidTMwd1liTGhJSEV0Q3cKaLsbYQfntceZWClaIGi36a+B/ou/qHMD
            di33xu/45vHSWWe6porz4DHYr4QsP0fWHOuEtdNZMWCqI9rvLCppwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T00:49:14Z"
    mac: ENC[AES256_GCM,data:PtI1cK0v/OtFlHV0INLhAoliNS0QHyK0Et/TIm02wdKEZzPBSoZ4r4SEEwSlDzSZTngYOOUGJFL58PTwH+p77mxCA2MgaBWu7JSbm0SzDS11HRb41OaZE9O6JcMo84pIU6cwQkimN5K4eB1Afv4RJ4Ok+SIbcGq4L/fADW4ObTI=,iv:ZjosAP8naVBN8vduJ6HO3Da6i0v9W7FhSPcKKpnExL0=,tag:IjSAdKkB+4TpPA8Eo9xaoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
