apiVersion: v1
kind: Secret
metadata:
  name: livekit-secrets
  namespace: meeting-automation
type: Opaque
stringData:
  LIVEKIT_API_KEY: "meeting-api-key"
  LIVEKIT_API_SECRET: "meeting-api-secret-2026"
