apiVersion: ENC[AES256_GCM,data:73M=,iv:shrFJiSHKhPGW3jHPSWyR5rJ/7WjjChmivxyEx5MfvQ=,tag:FFctTgE8GXGRW3gltOGq+Q==,type:str]
kind: ENC[AES256_GCM,data:LKdP50+W,iv:5LQ/lsB6ynyQsmAOuN/2b56NFu8OrSIbD6lEIwFCuLY=,tag:Crb8DYmmtRwHJ30TjLw5cA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mL7rW6WLwHqnKeefkQ==,iv:CmmOyzmvU4eB/hXe+fykk3gHagL7Zxg7LvcJctAm/58=,tag:mGG1QwLB37hd5rkT30x5QA==,type:str]
    namespace: ENC[AES256_GCM,data:z0maA4mRSbegx+sps9znHOb6,iv:ZQQ7ExFdoaxlmBeAUIg+iBTpwXIEJaJp1uuhDWmDUGo=,tag:BVobBHLrNI2Dtsnp/J8bxA==,type:str]
type: ENC[AES256_GCM,data:5XCLMOJ7,iv:bds/2xwRoYkBFuZZQqi/MfVv5rGSCsJKs7Kw8NEvtcs=,tag:aqgf0EOS+LS1+bggxg5RsQ==,type:str]
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:3AxyS9x3gt9Bzg==,iv:EKNsddxFzgshfk1o/yhapIWhsHdERS12aljAA8Td4KE=,tag:dEm4uhMD+gMIivhAr4U+2Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:8JLU3B+eV0Ru8q8odcPmrmAyJg==,iv:TAmalPWbALjZPTTN2CRsUsuEkamjoFg+WyxXvg9Agg4=,tag:lxTyUpGyP5l3jtmo+xTNNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZXNvUFVPY0NZbDFMSmlX
            d2ZVQmd5dXE1NE91Z1RwcXlSazJCaDRCVmdBCitlMVk4ck55VEhrUmdQQjBrOVhI
            VW4zalB1eS95SzMyWkdOV00yVko4SVEKLS0tIC9OTHlVcUZBOU9sQ2wxbEo0bTFD
            eGx4UGJtRmFIR05Ja2p4T2U0QUpoR0kKnZoX72kCjm7cnvEi085uQnjQ6wl0kl7d
            iBc/x67tBCVtwbuzw0aKHNp+V7wOt5nQhjfg8yopBmey6JIClvFUBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T23:55:32Z"
    mac: ENC[AES256_GCM,data:cqV4MmH8X6SNdKDkDk4xCW8xgWNdm3Zq+c7B3y91W441JfmRux8Yb8iqVkHrndpxpkUADNTBjKOCb/XKYaL6O130xL/VjQoAlTccyCXYDtMbwiA8Mff35E4QWG3Gh0oqJmcNsFNwbIgBV/B9IQ6fcR+p3nAnZzLIDSj9nwar6VI=,iv:5QT7H6q3+Q0ExzmZeAfax0iAEQxz3bLCpySeskh6+7g=,tag:q71z8LWqA5wiJU5wQ8wn7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
