apiVersion: ENC[AES256_GCM,data:Dr8=,iv:EinE0dinkXrhML9REYmQnwTrq9KMlDaYJX091bPXzzs=,tag:epcigbwWrOXiuNfB3gCJeg==,type:str]
kind: ENC[AES256_GCM,data:Bkxn9OBu,iv:e1Qm6k03GRm3+hQb+tC2aOORa9HIZ+avePMJWv+uAkw=,tag:4eWWKE0gULLMEJ1Iw7HrBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dcjOkzZiYM0AMUY8VQ==,iv:8ahOyOtR0+IBjiPdNxG7lvuneR3l1Ss/svrV9ECDP6w=,tag:2mMjMTXN8kVPvIqRp+ad1Q==,type:str]
    namespace: ENC[AES256_GCM,data:zIZoDdWRZTInajOBWphKiLlX,iv:NOQKvnrXS7ytHIWdtQsxc2EN3tJKK5w+aFJoEC0Aj2M=,tag:wULTrZDub173x+l6GfYSWA==,type:str]
type: ENC[AES256_GCM,data:jvgVH/4U,iv:KnYXQ/rlHsnxEM6WPGr6OXBqMTQTYf6u09br68RL8SE=,tag:ZcNlWaDD7JQkCN3WXPOkuw==,type:str]
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:tm2W6zP8Jg8JiA==,iv:UYa6vnDGdisK8+Vj4Mawg7TutDKBwWeDYxWavvn1Czg=,tag:+rik1+Vwpcf6FQlcFtrmJw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:YiV0dopShZ76hkOVEEI=,iv:cIQqfAwm9M7VMHrjSxBvzfV+XaHdM6ZpDHTuWzkebRA=,tag:Z76wkVEZQ6y2b8GCPWYzEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyrjgyvppvvatk9ngf03mn28wqd0pmx5frq02gmrcms3cz4t5chqwwn0kh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZXd1dGY4dGg4cXd5NGJo
            N3BCVUZZSUd6NEgzVU1BT3JNdjZ0czcwUEdrCjNHQnJ3LysvRHlCUGpheGpmbHpJ
            ZWJrTjJvTUQxcDYvZ3MrTnBMQUhac2sKLS0tIGowOTRNV1VrNnFoNUR0bUVGb2xm
            a0RReWFaRDZzZHEyaHlOeG8wRlVPWGMKZX7BB+uuE907fd9p+55dQRIFQFhi0eyu
            B3upltznmD5ZUclsKfRt2QKANIqf2HrIVUdSWYPamvcbLCXoD+OP9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:52:28Z"
    mac: ENC[AES256_GCM,data:Z+BifSkdGSwUA9ZxDzZZgoN7n6AQyBkNKlwGR7p/AuqsLW6G228dlTOAeeiMRAxpEv1qoCO2EXWqXh4pUJvbrLPUi4Z2JCt8eVPvDTugfra/m7u2bdD41sGqXqKMntj4opSPMP42/+/2L8s0PNKDeU8UOVXkvnlPvwDgqeDDvCk=,iv:bqo34XqPt2sbmr7vX9z6D8IKC2YTQtEayIftk0+ThuI=,tag:vpfuuAyLBuj3mXX/uq8/Zw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
