apiVersion: ENC[AES256_GCM,data:29w=,iv:fyJFzBeuZ/IuqnVxfWFmGKTGNxWLkveaSbesyuEnK8Y=,tag:GSdDW3oPg3Fa3My8+Kzw5g==,type:str]
kind: ENC[AES256_GCM,data:t/D2KKgC,iv:a6bGhf2M5rgPw7UdxSxFAfx0Yfxt9UagIJ/BfwUt49g=,tag:R18PcP1fxUSg3+XusdbURQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:atobeFApAlu+1Oc=,iv:mh6FmChGPw0jr96v/coJjPStW4qfLmv4jQskwEIe87U=,tag:jBurBQV/WkGj+N0NhRlHYg==,type:str]
    namespace: ENC[AES256_GCM,data:Ce4metJzMpq+Hl+d57bj1jGR,iv:LhV/gZa44TJeVbwePNCc5gyLneyyQ8XYZNwmZaewwW4=,tag:jUQ4rvU9w/iJT7mOdX1Bzg==,type:str]
type: ENC[AES256_GCM,data:XHATJlmb,iv:uA1komH1mV0iyC8VQeYJ/0uSUQkRasBgOrnA0RpC9js=,tag:pmcmZi5XV9TmTCC+ut+9lg==,type:str]
stringData:
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:Bj5KSIotA6Mts16M,iv:2PUaX/EBopZm0/pvHuk+YSSZCZaB7x7ZKXYaQbW4IzM=,tag:zw7SZ8BjxfgoRW+6rDKnpQ==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:WRigF1zEjNgpEP6LSttZqw==,iv:5vHatWuio2TKkLlkJUUNesO4ob9XOqVxcePe2IfqVik=,tag:yafjKHEsBvzs2r7b4Kezow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyrjgyvppvvatk9ngf03mn28wqd0pmx5frq02gmrcms3cz4t5chqwwn0kh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YmxZU2tmM3Mzb1pwS1NR
            MUxWMC81TFZ5TU9oLzJ4RlRXTDQxZ2ZML1NFClRNR0o0Snd0WER0VE5LeCtHTjZQ
            QlN3STFtQzYvNHQxK0JDR1BUengzMEkKLS0tIHhyM1NpT1lZazZmcTlBRGdiZ3Jt
            eURDVTlmNkF0Q2dRbHBJeG5YV002QWMKl3FUxhlMnpxosVXoilODYG5UtD+NSLXm
            kunvCM0rx5Op8PO89tN5Alu0PLFG4ZBmf7VUTeVA+cZJjYjc4mMcIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:52:28Z"
    mac: ENC[AES256_GCM,data:lBZpACy8w/sBScAElIstJCKLldFIxfBMC2WTTpyZm+zVEsRyTlcSr6+ERhGJ/Er6CNmJfX2wZwHKZMI6lLNT7adI/AMPIen2731TIVsnP61otYElg7d+7eWSE+ZyhZNzjebuLB38WLuC6zWUSjvBUPbY/v/zhDEK2Y00TxhKHt4=,iv:ewwlPx+A465+sJIYiUVA4tV7dw4jihQWTaWcEAehsrw=,tag:ZiIVJ53cLvUfbvabe0WvAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
