apiVersion: ENC[AES256_GCM,data:tA4=,iv:Avd5zvqyI3Fs0Lz8RtGAOyChfuPnZvaNQMfAgRaJCXc=,tag:KHMv89UWMeGUJxgSRMsVKA==,type:str]
kind: ENC[AES256_GCM,data:kzm6qWOr,iv:jq5XrY/m5ykZih3FldEQG5tPfVUriU65px/w5Vu3dBk=,tag:QOpuLmCMzXEzprCq1eO+ag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XmtVg4490JRPyfo=,iv:jk7Z2AVRO7e/YPF5b36bNMlTzS87L31IfcfKo4xsiV8=,tag:IZHkIhlPJ0V/i5FYHUcjVw==,type:str]
    namespace: ENC[AES256_GCM,data:Rap688VfLH47xhGKMM6FBwFu,iv:X/xUCTg7sJFtGMVJd779/eiaSjjwLi9gjaeX1BMCQ9A=,tag:+CCEeufSwQdgWu1SxfUCRg==,type:str]
type: ENC[AES256_GCM,data:oEpYBvwQ,iv:oKFjHfd9Tk/xMGO9ywNAfIZXDuFUB6cxD2r0JOJdXkY=,tag:p4tRL9qu7C6r2uQJpQ6rRA==,type:str]
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ZL8ThSmGlDJ2C1Tj/PWW0AGToZGPq9bSJZtZTg==,iv:NrMBq6wmNdPaeBL/uuziaDzPPp5inu7LVxwjkhs9GYM=,tag:sLHPP0Ze6P0EAM6E0+UP8A==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:9eYIBCOdljiRasYfu+/enULPbYv/,iv:l9/JhBS454vu5fCnMkaxnBKHat3VrDPjgBq30isRQl0=,tag:yUy2M163tbJT8hRozRAV0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArR2V4Y1FUOHQrV0xFYkt6
            SHRJdHZyTzBnV3hXUTZwZUl0SWVLc1NwU2tZCmIzMUl0SGx3cVorZ05zamxXRXN4
            ZWhURkw5L0NkSmI4NU1Lc2NRd243eGsKLS0tIEh6RmJrNk9hYnVMLzJPUE9CWG5y
            aHpZSnNJdnhtSjVZbjdxWUVBZ0dqQmMKlE9fYYKDff3tDELeP6gMkE03mE2Qb8Dv
            d7kk2otP7fO1GcnxyVf0VcF7VeYvuU+HQ9Aov9kqPCv8t+bqLx6niw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T23:55:32Z"
    mac: ENC[AES256_GCM,data:Hh2rw/a/dsBgxPX42IXuVb4eq3/CA0ztSB7u7CmP66vsUpzNnMUwBGdXunU9OhQH0ZOWvDWeijdYxu0o6vrefAeTZrXGlZ5F9fzFg/ssqLKGUCTHeuS8phKxLFl3cG2/jju/xGuJGMP0G5tAJ/URvARBiVxqvUDLkYRTWq5A7d4=,iv:3cPn4vcS6h05ZSflxB7/0ewTfyuXvRb/gmqUJqa/88Q=,tag:xDuekWVMQamO8FdZxUKI9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
