apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-data-pvc
  namespace: meeting-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-logs-pvc
  namespace: meeting-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi