apiVersion: ENC[AES256_GCM,data:rJs=,iv:l8joYN3NRFO/qvin27OzWaGm2okjGWZtGTd6GWr6lh8=,tag:g7p8Nh5UrYqVDjtJCXAidg==,type:str]
kind: ENC[AES256_GCM,data:wNTST78b,iv:Du0qLJJ5g46jmX4air5vvGHy27qSZ0tT/ZoSj940PXM=,tag:l2srNrukIfQSTGudN/MfSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7OYq/nCcaxfOMToVHLkrY9s=,iv:hJDJTSK5+KgIuMiZyXIbxO59gyTBf5C2PeoxRDhm1xE=,tag:SJDa8f5oA62oaUGLjFtUjg==,type:str]
    namespace: ENC[AES256_GCM,data:NIm6XiYgDlZDQp4CUIAcFRPC,iv:aD7c1mnyp/VwIeghJvBM2u0OkxG/6gtBpykboHD2eU8=,tag:GRa8Z8JvMp8MKN31nOf51g==,type:str]
type: ENC[AES256_GCM,data:ViOVvxYq,iv:01MlrqsJeOVE10g3Zc6hMAeuJlROm4g4uQrRWxm7cMY=,tag:NxUCECqb0i3lyC0j6B0AsA==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:hMNMPkiSQwR2jAn2H7E3eX0rQsmbeHnDGfyPBmIRgJyVgc1X5MX/evm45YiR2IzCsg==,iv:rPymvz4VWbJi0FifNPqntulb7MBQ8flV1het2KalSgU=,tag:ptjOsrA8uU1NGH9aaQ+eTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVhDaVBMekY4c2prRC9p
            clNmZG53MmFtckcwbmVVazFwY1dmSEF5RkZNCnBuSGwvbWRpZVdMV29ETTRPMVdT
            Vm15bXgzSHB6VE1CY0xqcXl4U0ZWcU0KLS0tIDJmY3d6YmdEVXhkOEs1ejlVRk5Y
            aW9MdS9XbmMvNm1nRXBBZVQ2OTZjY1EKx8d0sJ5jaDaY4Pedyme+ERLVPc6G9PPa
            1AxPvV+WyruPJyV/sjlF86klz9cG4aMFj58vjm5tH1u5lnKpLmr+5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T17:55:09Z"
    mac: ENC[AES256_GCM,data:Zzv/+ihutz88w22SoP0aAjzfdt4N7rPHc+/1PD/zjTyRaOUiWfmbPHLrjBQbPjpQNN1SLYK9BPbI/UiN7dL+IWrincdcvsTrnWKvCEVfUw7m1gkYTY3RVyictzWDiTgXb5JNUYzysECMHjjZZskHaMhBrmlic31MwycfU1DGHd0=,iv:wA9Jv0Wu4QJwijDJRPkeowYLdJL/jeZQu5nqFjEZjdE=,tag:73JeT/W6T71CgA58E5aErQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
