apiVersion: ENC[AES256_GCM,data:ZYw=,iv:kgQS5byK2T+2zy6sraKuAp+74Z/gsI2SiZ5JVgjBLcg=,tag:oKMQ9McvnRgKQVvwrhUBVg==,type:str]
kind: ENC[AES256_GCM,data:EJ5k3jyo,iv:5puTji/NO3HM5yTTOthAuVyFd8WuYwbTZuIjTLumjlY=,tag:MBEhTBeW2V9dpJpMw/e6vQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:maR24oR6PFXrM+ObvTTuNw==,iv:Thf0XuuxD+Xpu7GlN5StE8av1VGpoyEYJvEgKtvBJdY=,tag:Bi6tnozKWR0sAxX9MTwZcg==,type:str]
    namespace: ENC[AES256_GCM,data:hZmGZsOE/MOKS7OMHyoaPYNU,iv:By8k1t41Oq3E6MnZE6ldrPvyWcql8qumdPXB3hMbyHQ=,tag:spT4/meWK08wO69NrgUiWw==,type:str]
type: ENC[AES256_GCM,data:ORpYHydJ,iv:AFg+K07oIOx4k6PTxqQTrZc6dDFcAjs3kn5u5X1i1S0=,tag:s54qYuIbkZrpmfxGHwSYsw==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:nteTUzo5B0xPjr1C,iv:7b22bjNLt9OqHTTff2htw6yA2yJBR/xrFLhznlKfZ/I=,tag:wVxmtU1rhqvYB8aSQef4qw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fUyYqWdKArfAPc4uo4pJ/Lr5UkSz,iv:BX6Ti5jBR9aK2HkXdZEBkQO58i6hEkttmEdfDLvJ90U=,tag:AhAMc0BIDbvz95G4WVjNZw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:+stT7lQeM3sTFg==,iv:JXBjGquDy+zIi0dFyLMYXmRPuv78x9oZEFhaP4oONuA=,tag:x/kp1kLiqof3dpABVThMmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYnBJZWhKK0FWM1VPVFgr
            ZWwyLytQNDVRNHdRQ25OTndkV3FZOHRSVmlRCk44SEo4Z3ZkTlVqdyt6ZXNqZ1dP
            dHdYNnlBK2NNZE5sSUJ2VUtWL0VFNG8KLS0tIDgrVWNnU2JaNHFnT2p5b0gxOHNW
            WnZEdlp6YVpSNTJGR2ZHV0hHOFMyamcKMJtoGSv8HQWJOPfyss7abManuLldH28R
            IuuhpwmXyevclDWTLS3L60HZXnkBPxHZ2qsWZKKHA57Ax67MJ312yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T23:54:11Z"
    mac: ENC[AES256_GCM,data:TW5yKE8IA2TKhcz3FxBjCD4N/Jy8qVDnexwCINz/vnLXGZQ7DPGyFfzn5bNFLgIQoa1qgMwwByFKE8cbkIOB82hszsbaA1zJUfKph8OuEAqFj3HnHAC12pXWUJr2+utS5WZZD9b82/a7Vmp0Nit808j3X5J5T3q/RJSJ/OyxNnA=,iv:A2HEKUoR2/b8/JIR2Yq8aYMtE15eyzF/PsCFCyTUMuk=,tag:IGz8YM2t2xuE3aM/ibqnDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
