apiVersion: ENC[AES256_GCM,data:Gcs=,iv:MpDW0dOjlhd/EmAVl4MrzWdopwNDC4lZjN+Mh/cHy3U=,tag:2PfW/jy5i9cq8G39pcr19g==,type:str]
kind: ENC[AES256_GCM,data:eKLOxT7+,iv:uIbEaUvOvO755WzIRtv797758HKTpdCSpRpCGepdNXg=,tag:95d5ywDCPUeJ8wZATxP6sg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PPmnEA50mRwhJQXN8L2PLA==,iv:/A/pE5zNNCi5pB4+OUNcmz+o+avLgsxlAybrJvVfVd0=,tag:VMvOwf7lzKJZufGUFEuqYw==,type:str]
    namespace: ENC[AES256_GCM,data:iW2JXa2Midb/MdgKWuNEDwGl,iv:PYKyXDjLsU2dwEkjwUUuPOXnp/U9oTBlsHwBjufqRQg=,tag:3taaYk49tZS8sqn9nMbR+A==,type:str]
type: ENC[AES256_GCM,data:V4LyboKY,iv:v1SjSS77mrjfr+eaNkYb044DVLuB2FdfdSSv6eawmW4=,tag:PjiLgirljp7NB+g3EBtPQQ==,type:str]
stringData:
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:B6OmutYQm8Bg280=,iv:yIkaji9G6sxFFHGW5eTm/Y9NxukbKAFkayKeNE1HuQg=,tag:/cCXtuN6Q5z72anC3qD0qA==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:h35uIxHyV2brje6bBQhbhtAtsw0=,iv:8hz3/ZUwj6U017Lq8atW+uO/7Cpp4PLCNJwFnNRAL3g=,tag:bdyxTHkyKPb6DHMSpBpveA==,type:str]
    RABBITMQ_ERLANG_COOKIE: ENC[AES256_GCM,data:4L2raj7NM9n2AKpfiqYe8+P62nfYpsKHIRathNVQPxQ=,iv:1XGbO8kWYpkCjPkwK2cyBYkBPA7QYByLF1byCAuVq6Q=,tag:3umSSyx1HfOUIU0/ONjtZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZE1pVHByclBMQ0VZeEQ3
            VDkzSk5UYzNJUlR0aE12UytzVGRYSzZTbERnCjRDUkFOaTg1UEZnN3hONm5ZdTlj
            UndjQnRkRHFIcU5GRVZoTGFtaWFDN2sKLS0tIForTndWcUdhWXdHbEIzZHoyUkhm
            YXl4QzlTL1d0RG03Q2NubEpyOTNrVVkKXxlB4sSvOq9vJ6BfpIeyPw+P1POY9tuZ
            DMSkUx6nzSxOTo+2v5M2A6HMmY4knDE+QfZIYDKC8i0fHTu7umvM5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T23:55:32Z"
    mac: ENC[AES256_GCM,data:w+XgxF6j9kdwUp0efIFTmasa4ZcNKFi1nSZMbv5w8X4OPEq0k14zpu8pDhCnFxRRM+908CgdWD0lLyGnxokJFPwJRsaL/jE00SxhiKs8/8sUH+jcB0ovT0cAcY/xnW+xgtqmrcW85atoSPYQkF+bhtrUZCpG7q4ta1orMAC4Ov4=,iv:YJ2DC3T9ORA9VDpc00BIFWXBEljidHI3dLAImtvEZPo=,tag:dpFyh13TX0FtlCeFXkZ3gQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
