apiVersion: ENC[AES256_GCM,data:+EU=,iv:hmbJy/Oy3pz41LdjkhK7Lf/hmNdevwS+mWs2SEPNVC0=,tag:Mxo5U5Eyje9YaiVWZ049jQ==,type:str]
kind: ENC[AES256_GCM,data:/jQ2TrxB,iv:q5WJlijUoIEeRHx24N3j0lu3CyBeaNMWidLisVsUi9w=,tag:i+dAI7LKZ7gJkJDqo+XRlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ddmp5Gsj9ef2DLVC2w==,iv:XdR+e51KGzyDukTFgY/eIG0FPXwPDia5fJYhA6iqGJs=,tag:U+hZ8Q5qm7fN4kkl4m36YQ==,type:str]
    namespace: ENC[AES256_GCM,data:TSM+xe8i3zRAUM1xL3FDRSaf,iv:izwBXtkRlCb2E225GNpgL0zEtWVcczecKA30TDez1fU=,tag:YrGgNvvIYxx25yeNnAQn3w==,type:str]
type: ENC[AES256_GCM,data:KD8utwiU,iv:P36EG5B02YX4FOZgRjXXCQoj7/cvOWLbl7ONtsObO3A=,tag:B+ISC9nQbfwl5j7XrL5BUw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:xgYUNW3UYNE+al61VZc=,iv:XQZoi4DAcz72DQCY02owyjWwXndu7/P7VYVbKSZ606M=,tag:nHp4ldZYsOm9ryRtDsBlww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyrjgyvppvvatk9ngf03mn28wqd0pmx5frq02gmrcms3cz4t5chqwwn0kh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aWw0ZElCOGxZeUdkcHp2
            Um1ZZVladVU4cUo4YkVyNitjbDhhdEdyUlUwCms1dzRMdHV4ZWJQYVdzVnppM3NR
            SllFcEJBMGc1NkY3MTladFNwNHFZK2sKLS0tIHFnN2JjbEJ5c0VBMHRkV1NRL0d1
            VTVEY3Uyb3NDQnk1dUsxM3pwTm0xSU0KlAXixXHVpS8b8woA1SndVrvNTXbYtPzM
            URfwehSNhKaYlpajr6F1oysgO/3PKneivwwgYRtFJFqX8iZyjn1JWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:29:22Z"
    mac: ENC[AES256_GCM,data:JP6FlEPIg4Avtlrny4/tG33SeYYzd01XH0D5K2Mj+IgJVQxfJHFbRL7z0zsVurPs/sijgQZq7ElT5gx0C5XydLFU0Ef91jN1aM+MjserWls+qn8wRmSNohqGStYqvCIhKRBN8HY/+KRukITcmz5ovX1HQ/HVkqCpb+5k54WlAeg=,iv:lH9lZJHa9TKj5nGYIklItJzX17rddw5hMAFqapb/SCI=,tag:DR3QC+C/zqiZgSnlIzxv4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
