apiVersion: ENC[AES256_GCM,data:cPQ=,iv:iUnptS7bgeEjt7lOcHetGqUyK9KEmL/X29XMBGOjK3U=,tag:KQ1QGFAnUpiPGmfChafEcA==,type:str]
kind: ENC[AES256_GCM,data:ci8Iy09B,iv:TC1y8Mgc+wajIaUDsztiKGL3XKoek5vyoTDhC9mFVD4=,tag:ctVtbfPyQJ4qrQpYtFQOGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:95AYSySaSwj07aaSSQ==,iv:dTHFAzf77hMbAz6x6IhNimcLP/rz6goVnojJkNBfZak=,tag:5PsCP8c0s2BGDONLIhEOMQ==,type:str]
    namespace: ENC[AES256_GCM,data:IMTEzO5qrmQsjWcf4hvYRsO4,iv:2mWbO75zWqUq2SnlAm/pX5nzaJKWwztGHoS7tt3wwyo=,tag:C8nJCQw04OCoT26cJ2DbPA==,type:str]
type: ENC[AES256_GCM,data:p2IO/t5z,iv:/nW7+9JuAoiPxoVXMvAw30veEelDOPcl6fZaGkFBUUA=,tag:GOinyM6BGE8noVljxjlVqw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:+bDyZedfqzIN9uOLXdCTuCOY2A==,iv:YlpfrbA8uBFG9nH6wlU41awNE0AXcGmO3OAmfsj0PAM=,tag:lqJ+dANO4vcT/Q2wIISvsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f8u7gjf284d0ecr5x5uwshl9f96l4afxh0x2dlfa8rev5wm8u3smllfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZGFiVnQrZG9UQWFvSllN
            WkFxU2pORnFxT2hDV0tMZ3lHUTk1Q3YzZVdZClE4Wk9oUnhBaUhodnVaWmpGVDNO
            ajhhNXV2VXNQSlpLbExXdWJkNlRiUlEKLS0tIHBvWWpDTTRDZElwOERxRlU1Z1Za
            akxTczJKR3A3SHlNMVVVdHdUcHJMNGsKz33FzrWtWDOqtj7o40HUviV05HE8/Kr5
            NiIua/InqPiszl9XXMxN9yRiSPDbJaHEDdu2fJP8eQnfUIEvpO5kvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T00:17:23Z"
    mac: ENC[AES256_GCM,data:Cl5YeN/c5LSDOk8qmNC0FLg1umYq5yrVePxbWbHY6HibH0QZAamnfk1i96V2f/mq7zOcbYFhJzmNV3f6fJjfgu0ISQaUB4tgE5eYZbavfMAQQ9mpQ4FDStLAHp0PNw08WZYo/Dq6WhU2vXKiK3y9/qAsVVAQxRFz2FBeQS3EWbk=,iv:EglY4/hNcqBeseKDcigX9aBCUBVE7XL4G01Otsv93Ik=,tag:FfznrsD/GIUGO2+eP25TlQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
